GET http://localhost:3333/tarefas

### 
GET http://localhost:3333/tarefas/5

### 
POST http://localhost:3333/tarefas
Content-Type: application/json

{
  "name": "Estudar React"
}

### 
PUT http://localhost:3333/tarefas/4
Content-Type: application/json

{
  
  "name": "Estudar Docker"
}

### 
DELETE http://localhost:3333/tarefas/3
